### PR TITLE
Update SDL_ts link in languages.php

### PR DESCRIPTION
**Pull request by smack0007**
Hi I'm the maintainer of SDL_ts and I'm glad @jingkaimori took the time to add this here but I would prefer the link pointed to the GitHub repo. The current link points to a specific version of SDL_ts and I haven't updated that place in 8 months at this point.

### CODE REVIEW

**Comment by smack0007** [comment]
Any chance of getting this merged?

**Comment by slouken** [comment]
Yep! Merged, thanks!

**Comment by smack0007** [comment]
Hey great! Thanks a lot.

**Comment by slouken** [comment]
You're welcome!

**Pull request merged**
