### PR TITLE
Change font to Poppins

### PR DESCRIPTION
**Pull request by rivercory**
@slouken Changed font to Poppins for better readability!

### CODE REVIEW

**Comment by slouken** [comment]
Can you add a screenshot so we can see what this looks like?

**Comment by icculus** [comment]
Looks the same to me: https://staging.icculus.org/ vs https://www.libsdl.org/

Maybe it didn't load the font?

**Comment by rivercory** [comment]
> Can you add a screenshot so we can see what this looks like?

화면 캡처 2024-09-06 153046

**Comment by rivercory** [comment]
> Looks the same to me: https://staging.icculus.org/ vs https://www.libsdl.org/
> 
> Maybe it didn't load the font?

I'm sorry. I didn't apply Poppins font.
This has been fixed with this commit: https://github.com/libsdl-org/sdlweb/pull/23/commits/5a6bf961e98e79894ba2685c1abcf8ded0a9643f

**Comment by icculus** [comment]
I've updated https://staging.icculus.org/ if you want to compare it vs https://libsdl.org/ , @slouken.

**Review by slouken — APPROVED** [review]
My wife gives it the thumbs up :)

**Comment by icculus** [comment]
Okay, this is live on the website, thank you!

**Comment by rivercory** [comment]
@slouken @icculus Thanks :)

**Comment by slouken** [comment]
Thank you!

**Pull request merged**
